# Generated by Django 5.0.6 on 2024-05-14 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
